### ISSUE TITLE
devmode fails with missing private keys?

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-renarde#12]
I just have a controller class and index.html (the hello world from docs) and it works when I package/run it, but when I run in devmode I get this error:

```
java.io.FileNotFoundException: target/classes/dev.privateKey.pem (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at io.quarkiverse.renarde.deployment.RenardeProcessor.setupJWT(RenardeProcessor.java:228)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Resulted in: java.lang.IllegalStateException: java.io.FileNotFoundException: target/classes/dev.privateKey.pem (No such file or directory)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:934)
	... 6 more
Resulted in: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.renarde.deployment.RenardeProcessor#setupJWT threw an exception: java.lang.IllegalStateException: java.io.FileNotFoundException: target/classes/dev.privateKey.pem (No such file or directory)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:934)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Resulted in: java.io.FileNotFoundException: target/classes/dev.privateKey.pem (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at io.quarkiverse.renarde.deployment.RenardeProcessor.setupJWT(RenardeProcessor.java:228)
```

I haven't configured any JWT (yet) and also don't need it just yet ...shouldn't renarde be resilient and let me get started without JWT setup?

**Comment by maxandersen** [comment]
https://github.com/maxandersen/renard-jbang-demo/tree/quarkus-renarde-12/src has the example.

`jbang src/Main.java` works but `jbang -Dquarkus.dev --fresh src/Main.java` fails

**Comment by FroMage** [comment]
That's weird, because those files are only created in dev mode.

**Comment by maxandersen** [comment]
Created how by what ? Maybe we got a bug in how renarde and jbang quarkus Interact during devmode?

**Comment by maxandersen** [comment]
Ie. There is no target/classes in jbang so I wonder where you get that path from?

**Comment by maxandersen** [comment]
But still - why should those jwt resources be required when not using it (yet) ?

**Comment by FroMage** [comment]
Created by the renarde processor, because JWT needs them and will complain otherwise

**Comment by FroMage** [comment]
OK, I get it now, this is where I put the generated files, so that Maven picks it up. Since this is not a Maven project it doesn't work. So where should I place generated files for JBang, then @maxandersen ?

**Comment by maxandersen** [comment]
As GeneratedResourceBuildItem I believe ?

@stuartwdouglas @aloubyansky that should work even for jbang, right ?

**Comment by maxandersen** [comment]
But still - why is JWT enabled when not using it ? Is that a prerequisite for using renarde ?

**Comment by aloubyansky** [comment]
Right. Haven't looked into how Renarde does it but if it's hard coded assumptions about classes location it's a trap even for some Maven projects. Bootstrap actually provides api that can be used to locate the classes dir. @FroMage let me know if you want me to have a look at that part for you.

**Comment by FroMage** [comment]
If I use a `GeneratedResourceBuildItem` then the keys change on every restart. I wanted to create them exactly once and keep them around, otherwise the user token becomes invalid after every restart.

**Comment by maxandersen** [comment]
Hmm - how does Grpc code gen works ? It shouldn't regenerate every time..

**Comment by FroMage** [comment]
Isn't that a special Maven plugin?

**Comment by FroMage** [comment]
Yes, it's in the generate phase

**Comment by FroMage** [comment]
@aloubyansky can I get access to the `Bootstrap` info from a build step?

**Comment by maxandersen** [comment]
It's part of quarkus plug-in so default configured in new projects. 

But if you need something "surviving" clean or even just restart I can't see how you do it cleanly without a generate phase ?

**Comment by FroMage** [comment]
It won't survive `clean`, but it will survive restarts.

**Comment by BastiOfBerlin** [comment]
I get the same error using a Gradle build setup.

**Comment by PraveenGandhi** [comment]
I get the same error with gradle.

**Comment by TeHMoroS** [comment]
Same problem with Gradle, as the two comments above. I've had a warking Gradle build and as I was on an early stage, I decided it's a good moment to experiment and try out Renarde. After adding the dependency, creating a few simple controllers and templates (based on the starter examples) and trying to run it in dev mode, I've got the missing keys error.

I managed to do a fest recreation of the issue. A few days ago I made a simple project for a feature suggestion to Quinoa: https://github.com/TeHMoroS/quinoa-watch-issue

To recreate the issue with this project you just need to clone it, add:

`implementation "io.quarkiverse.renarde:quarkus-renarde:1.0.1"`

to the `dependencies` in `build.gradle` and run the dev more:

`./gradlew clean quarkusDev`

It will result in the error showing:
```
2022-06-02 10:18:58,157 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.renarde.deployment.RenardeProcessor#setupJWT threw an exception: java.lang.IllegalStateException: java.io.FileNotFoundException: target/classes/dev.privateKey.pem (No such file or directory)
```

**Comment by FroMage** [comment]
Thanks. I wanted to help users not have to generate the keys, but this turns out to be very annoying.

@aloubyansky I tried `CurateOutcomeBuildItem.getApplicationModel().getAppArtifact().getWorkspaceModule().getBuildDir()` but it gives me `target` instead of `target/classes` for Maven. I haven't tried for Gradle yet but already this is not what I expected.

**Comment by FroMage** [comment]
Gradle says the folder is `build` and I can see a `build/classes` folder there. Perhaps I can just assume that both Gradle and Maven have a `classes` folder that ends up in the classpath, I wonder.

**Comment by aloubyansky** [comment]
> @aloubyansky I tried `CurateOutcomeBuildItem.getApplicationModel().getAppArtifact().getWorkspaceModule().getBuildDir()` but it gives me `target` instead of `target/classes` for Maven. I haven't tried for Gradle yet but already this is not what I expected.

I see. In this case, you could do something like
````
ArtifactSources src = curateOutcomeBuildItem.getApplicationModel().getAppArtifact().getSources();
if(src != null) { // shouldn't be null in dev mode
    Collection<SourceDir> srcDirs = src.getResourceDirs();
    if(srcDirs.isEmpty()) {
        // in the module has no resources dir?
        srcDirs = src.getSourceDirs();
        if(srcDirs.isEmpty()) {
             // TODO the module doesn't have any sources nor resources
        }
    }
    // pick the first resources output dir
    Path resourcesOutputDIr = srcDirs.iterator().next().getOutputDir();
}
````

**Comment by TeHMoroS** [comment]
I was able to test it a bit further and with Gradle, there's now a new problem: after launching the app in dev mode, I get the exception:

```
2022-06-02 20:28:08,409 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to / failed, error id: 9a6f9d93-7bbd-4b57-9579-f93059c72cd3-1: javax.enterprise.inject.spi.DeploymentException: SRJWT02002: Failed to read the public key content from 'mp.jwt.verify.publickey.location'
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider.getOptionalContextInfo(JWTAuthContextInfoProvider.java:475)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_Subclass.getOptionalContextInfo$$superforward1(Unknown Source)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
[...cut out a bit for brevity...]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.MalformedURLException: no protocol: dev.publicKey.pem
	at java.base/java.net.URL.<init>(URL.java:674)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at io.smallrye.jwt.util.ResourceUtils$UrlStreamResolver.resolve(ResourceUtils.java:110)
	at io.smallrye.jwt.util.ResourceUtils.getResourceStream(ResourceUtils.java:81)
	at io.smallrye.jwt.util.ResourceUtils.readResource(ResourceUtils.java:44)
	at io.smallrye.jwt.util.ResourceUtils.readResource(ResourceUtils.java:39)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider.getOptionalContextInfo(JWTAuthContextInfoProvider.java:470)
	... 73 more
```

First this I did, was to copy the keys from `build/classes` to `build/classes/java/main` as the path in my previous comment suggested was the current working directory. It worked, so it seems that changing the path in the build process was step 1. The next step would be to do the same for reading the keys in in runtime.

**Comment by aloubyansky** [comment]
Just fyi, I've seen quite a few reproducers in other issues where the main app module has no sources. So checking for resources dirs would make sense (also that's where generated resources would belong), given that those sourceless projects will likely have an `application.properties` and/or other config. It'd be a good idea to test a project with the main module containing no sources nor resources at all.

**Comment by FroMage** [comment]
And thanks everyone for testing and helping :)

**Comment by TeHMoroS** [comment]
@FroMage Just switched and tested. Works well in my case. :)
