### ISSUE TITLE
Localisation working in 'dev mode', but not in packaged application

### ISSUE THREAD

**Issue by horvie** [quarkiverse/quarkus-renarde#124]
When running my application in dev mode everything works great. But when I package my application and run it from command line, **RenardeConfig.addLanguageBundle** tries to locate message files from absolute path of project workspace and not from application package. I get exception:

<pre>
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 15 more
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/user/workspace/app-name/target/classes/messages_en.properties
	at io.quarkiverse.renarde.impl.RenardeConfig.addLanguageBundle(RenardeConfig.java:43)
	at io.quarkiverse.renarde.impl.RenardeConfig_ClientProxy.addLanguageBundle(Unknown Source)
	at io.quarkiverse.renarde.impl.RenardeRecorder.addLanguageBundle(RenardeRecorder.java:16)
	at io.quarkus.deployment.steps.RenardeProcessor$findMessageFiles848786311.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.RenardeProcessor$findMessageFiles848786311.deploy(Unknown Source)
	... 16 more
Caused by: java.nio.file.NoSuchFileException: /home/user/workspace/app-name/target/classes/messages_en.properties
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
	at io.quarkiverse.renarde.impl.RenardeConfig.addLanguageBundle(RenardeConfig.java:40)
	... 20 more
</pre

**Comment by FroMage** [comment]
OK, this is something that is definitely working for me, so do you have a reproducer? We probably are doing things a little differently.

**Comment by horvie** [comment]
I am attaching a simple reproducer.
I forgot to mention before, that the packaged application runs on my computer, as the workspace folder is present. But it doesn't run on other computer or inside docker image.

```
mvn package
docker run --rm test/app:1.0-SNAPSHOT
```

[app.zip](https://github.com/quarkiverse/quarkus-renarde/files/11476574/app.zip)

**Comment by FroMage** [comment]
OK, it's in Maven Central, feel free to try `3.0.2` :)
