### ISSUE TITLE
Quarkus 3.1.1-Final compile error

### ISSUE THREAD

**Issue by tmulle** [quarkiverse/quarkus-renarde#137]
When updating to Quarkus 3.1.1-Final using Rendered 3.0.2 I get the compiler error below.

Quarkus `3.0.4-Final` works fine... once you get into `3.1.x-Final` it breaks. I tried both `3.1.0-Final` and `3.1.1-Final`

```[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.1.1.Final:build (default) on project qute-support-site: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: jakarta.enterprise.inject.spi.DefinitionException: Declaring class of a managed bean is generic, its scope must be @Dependent: com.rajant.support.site.rest.BaseControllerWithUser
[ERROR] 	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1282)
[ERROR] 	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:52)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1121)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:266)
[ERROR] 	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:142)
[ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:443)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

This is my `BaseControllerWithUser` class which I've been using just fine in previous releases. I'm including it here since the error called out this class.

```
/**
 * Extension of Renarde Controller to provide convience methods
 *
 * @param <U> User type
 */
public class BaseControllerWithUser<U extends RenardeUser> extends ControllerWithUser<U> {


    protected Response ok(Object entity) {
        return Response.ok(entity).build();
    }

    protected Response internalError(Throwable cause) {
        throw new WebApplicationException(cause, Response.Status.INTERNAL_SERVER_ERROR);
    }
    protected Response internalError(String message) {
        throw new WebApplicationException(
                RestResponse.ResponseBuilder.create(RestResponse.Status.INTERNAL_SERVER_ERROR, message).build().toResponse());
    }
    protected Response notFound(String message) {
        throw new WebApplicationException(
                RestResponse.ResponseBuilder.create(RestResponse.Status.NOT_FOUND, message).build().toResponse());
    }
    protected Response unauthorized(String message) {
        throw new WebApplicationException(
                RestResponse.ResponseBuilder.create(RestResponse.Status.UNAUTHORIZED, message).build().toResponse());
    }

//    protected Response badRequest(String message) {
//        throw new WebApplicationException(
//                RestResponse.ResponseBuilder.create(RestResponse.Status.BAD_REQUEST, message).build().toResponse());
//    }

    protected Response badRequest(Object entity) {
        throw new WebApplicationException(
                RestResponse.ResponseBuilder.create(RestResponse.Status.BAD_REQUEST, entity).build().toResponse());
    }

}
```

**Comment by tmulle** [comment]
@FroMage Yup, that worked!
