### ISSUE TITLE
jakarta.ws.rs.NotFoundException: Unable to find matching target resource method

### ISSUE THREAD

**Issue by tmulle** [quarkiverse/quarkus-renarde#173]
Not sure when this started but with Quarkus 3.4.1 and Renarde 3.0.3

I'm seeing a lot of these exceptions printing out on the console when accessing various parts of my Renarde based website.

Everything appears to be working fine security wise, I can log in, logout, access protected resources, etc.

The only thing I've upgrade was Quarkus version to the latest 3.4.1

I tried 3.0.4 of Renarde but that seems to break my JAX_RS endpoints.. they are not hit or I appear to not being logged in..
Anyway, that might be another ticket..

Just wanted to mention what I'm seeing with the current version.

```
jakarta.ws.rs.NotFoundException: Unable to find matching target resource method
	at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.throwNotFound(ClassRoutingHandler.java:231)
	at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.handle(ClassRoutingHandler.java:102)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:123)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:102)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:88)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
	at io.quarkiverse.renarde.util.AuthenticationFailedExceptionMapper.myFilter(AuthenticationFailedExceptionMapper.java:97)
	at io.quarkiverse.renarde.util.AuthenticationFailedExceptionMapper_RouteHandler_myFilter_dc247f9502a33787ac476eab0f2e905053c2515c.invoke(Unknown Source)
	```

**Comment by tmulle** [comment]
Hmm ok.. I turned on the Access logs in Quarkus and it appears to be related to HTML items not being found.

```
2023-10-02 16:00:55,941 INFO  [io.qua.htt.access-log] (vert.x-eventloop-thread-2) 0:0:0:0:0:0:0:1 - - [02/Oct/2023:16:00:55 -0400] "GET /css/bootstrap.min.css.map HTTP/1.1" 404 196
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-10-02 16:00:55,942 INFO  [io.qua.htt.access-log] (vert.x-eventloop-thread-9) 0:0:0:0:0:0:0:1 - - [02/Oct/2023:16:00:55 -0400] "GET /css/bootstrap-theme.min.css.map HTTP/1.1" 404 196
```

Not sure why I didn't see those exceptions on the console before.

**Comment by tmulle** [comment]
Is there a way to tell which resource is not being found?

I'm getting a lot of these exceptions (which I can't seem to turn off?)

Can you add the resource path to the exception message and add the exception as an ERROR log?

I only see these errors on the console and not in the log output, so I'm guessing it's doing a Exception.dumpStackTrace()?

```
jakarta.ws.rs.NotFoundException: Unable to find matching target resource method
        at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.throwNotFound(ClassRoutingHandler.java:231)
        at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.handle(ClassRoutingHandler.java:102)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:123)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:102)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:88)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.quarkiverse.renarde.util.AuthenticationFailedExceptionMapper.myFilter(AuthenticationFailedExceptionMapper.java:97)
        at io.quarkiverse.renarde.util.AuthenticationFailedExceptionMapper_RouteHandler_myFilter_dc247f9502a33787ac476eab0f2e905053c2515c.invoke(Unknown Source)
```

**Comment by FroMage** [comment]
Sorry, this is a version of AuthenticationFailedExceptionMapper` which is pretty old and got rewritten. I've answered the questions on your other issues about upgrading. If you can upgrade to the latest version of Renarde, can you reproduce, and if yes, give me a sample reproducer? I'm not seeing those errors myself.

And really sorry about the late replies :(

**Comment by tmulle** [comment]
No worries, I can't upgrade to the latest because of the login issue in my other ticket.

That's how I found the error in the first place was by upgrading to the latest version and then my login stopped working.

**Comment by FroMage** [comment]
Can you give me a reproducer project?

**Comment by tmulle** [comment]
I can't at the moment because I am seeing it my legacy application I mentioned in previous tickets.
I can try to make a reproducer tonight.

I'm trying to narrow it down to see if it is a 404 error for missing links, paths defined in the web pages trying to make AJAX calls or something.

I've enabled HTTP access log in Quarkus to help troubleshoot

**Comment by DaHoC** [comment]
Same request from my side to include the information about what resource was failed to access/resolve. I have up-to-date dependencies of io.quarkus:quarkus-rest 3.11.2.
I see the exception mapper in the included transitive dependency (quarkus-rest > resteasy-reactive-vertx > resteasy-reactive) in ~/.m2/repository/io/quarkus/resteasy/reactive/resteasy-reactive/3.11.2/resteasy-reactive-3.11.2.jar!/org/jboss/resteasy/reactive/server/handlers/ClassRoutingHandler.class line 236 omitting this information.

I prefer to have the information included in the Exception instead of the logs, because I use Sentry for error reporting which works best for this purpose with exceptions.

**Comment by FroMage** [comment]
Please open an enhancement PR in Quarkus core at https://github.com/quarkusio/quarkus/issues/new/choose

**Comment by DaHoC** [comment]
> Please open an enhancement PR in Quarkus core at https://github.com/quarkusio/quarkus/issues/new/choose

I was unable to locate the sources of this file after a short search, maybe you have a pointer so that I can open a Merge/Pull Request.

**Comment by FroMage** [comment]
It's here: https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ClassRoutingHandler.java
