### ISSUE TITLE
Renarde And native : Class not found

### ISSUE THREAD

**Issue by anthonydenecheau** [quarkiverse/quarkus-renarde#176]
Hi
Try to build a native within github action
> Native Image (org.graalvm.native-image, version 21.2.0)
> Java version: 17.0.8+7, vendor version: Mandrel-23.0.1.2-Final

Pom.xml
> quarkus.platform.version : 3.4.3
 > renarde.version :3.0.4

Error :
```
 4 user-specific feature(s)
 - io.quarkus.hibernate.validator.runtime.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.hibernate.validator.internal.util.Version] categories
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
 - org.eclipse.angus.activation.nativeimage.AngusActivationFeature
java.lang.ClassNotFoundException: org.apache.pdfbox.pdmodel.encryption.PublicKeySecurityHandler
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at io.quarkus.runner.Feature.runtimeInitializedClasses(Unknown Source)
	at io.quarkus.runner.Feature.beforeAnalysis(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:757)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:86)

```

**Comment by anthonydenecheau** [comment]
It seems to be ok with renarde.version :3.0.1

**Comment by FroMage** [comment]
I believe this is fixed in `main`, I will make a release ASAP.
