### ISSUE TITLE
Upgrading from Quarkus 3.9.4 to 3.10.0 throws BuildException/IllegalArgumentException

### ISSUE THREAD

**Issue by gbourant** [quarkiverse/quarkus-renarde#213]
I try to upgrade Renarde to use the latest Quarkus version (3.10.0) and it throws the following exception.
 
```
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#collectTemplates threw an exception: java.lang.IllegalArgumentException
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.relativize(ZipPath.java:248)
	at io.quarkus.qute.deployment.QuteProcessor.lambda$scanTemplateRootSubtree$12(QuteProcessor.java:3394)
	at io.quarkus.paths.FilteredPathTree.lambda$walk$0(FilteredPathTree.java:35)
	at io.quarkus.paths.PathTreeVisit.walk(PathTreeVisit.java:25)
	at io.quarkus.paths.ArchivePathTree.walk(ArchivePathTree.java:98)
	at io.quarkus.paths.FilteredPathTree.walk(FilteredPathTree.java:33)
	at io.quarkus.qute.deployment.QuteProcessor.scanTemplateRootSubtree(QuteProcessor.java:3391)
	at io.quarkus.qute.deployment.QuteProcessor.lambda$scanPathTree$7(QuteProcessor.java:2171)
	at io.quarkus.paths.PathTreeVisit.consume(PathTreeVisit.java:47)
	at io.quarkus.paths.ArchivePathTree.accept(ArchivePathTree.java:147)
	at io.quarkus.qute.deployment.QuteProcessor.scanPathTree(QuteProcessor.java:2168)
	at io.quarkus.qute.deployment.QuteProcessor.collectTemplates(QuteProcessor.java:2152)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:333)
	... 19 more
Caused by: java.lang.IllegalArgumentException
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.relativize(ZipPath.java:248)
	at io.quarkus.qute.deployment.QuteProcessor.lambda$scanTemplateRootSubtree$12(QuteProcessor.java:3394)
	at io.quarkus.paths.FilteredPathTree.lambda$walk$0(FilteredPathTree.java:35)
	at io.quarkus.paths.PathTreeVisit.walk(PathTreeVisit.java:25)
	at io.quarkus.paths.ArchivePathTree.walk(ArchivePathTree.java:98)
	at io.quarkus.paths.FilteredPathTree.walk(FilteredPathTree.java:33)
	at io.quarkus.qute.deployment.QuteProcessor.scanTemplateRootSubtree(QuteProcessor.java:3391)
	at io.quarkus.qute.deployment.QuteProcessor.lambda$scanPathTree$7(QuteProcessor.java:2171)
	at io.quarkus.paths.PathTreeVisit.consume(PathTreeVisit.java:47)
	at io.quarkus.paths.ArchivePathTree.accept(ArchivePathTree.java:147)
	at io.quarkus.qute.deployment.QuteProcessor.scanPathTree(QuteProcessor.java:2168)
	at io.quarkus.qute.deployment.QuteProcessor.collectTemplates(QuteProcessor.java:2152)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

**Comment by gbourant** [comment]
This is fixed in `3.11.0.CR1`

**Comment by FroMage** [comment]
Ah yes, we did notice in other issues, thanks for reporting, though :)
