### ISSUE TITLE
RedirectException

### ISSUE THREAD

**Issue by waleedESB** [quarkiverse/quarkus-renarde#239]
When I create or delete an instance of an entity in Renarde BackOffice Interface, the operation completes successfully, meaning the entity is created or deleted as expected. However, immediately after the operation, an exception is thrown. This exception does not seem to affect the outcome of the operation, but it suggests there might be an underlying issue that needs to be addressed.
Version: 3.0.18

` io.quarkiverse.renarde.util.RedirectException
        at io.quarkiverse.renarde.Controller.seeOther(Controller.java:109)
        at io.quarkiverse.renarde.Controller.seeOther(Controller.java:101)
        at rest._renarde.backoffice.AccountController.create(Unknown Source)
        at rest._renarde.backoffice.AccountController_Subclass.create$$superforward(Unknown Source)
        at rest._renarde.backoffice.AccountController_Subclass$$function$$3.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at rest._renarde.backoffice.AccountController_Subclass.create(Unknown Source)
        at rest._renarde.backoffice.AccountController_ClientProxy.create(Unknown Source)
        at rest._renarde.backoffice.AccountController$quarkusrestinvoker$create_a058539713198ba6babb9aa0287f1df749b3265d.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1570)
`

**Comment by FroMage** [comment]
Could you share a minimal reproducer project please?
