### ISSUE TITLE
Build Break: 'quarkus.oidc.auth-server-url' is required even when not using OIDC (Production Mode)

### ISSUE THREAD

**Issue by tmulle** [quarkiverse/quarkus-renarde#59]
Hello again,

Since we are just using JWT and JDBC for authentication we don't need any of the OIDC configuration settings.

However, when running our app in PROD mode we are required to add the configuration key:

`quarkus.oidc.auth-server-url`

So, to get around the error I entered:
`quarkus.oidc.auth-server-url=http://localhost` 

the stops the build time error however upon startup we get a WARN and the application seems to run fine so far.

It seems that most security on Quarkus assumes everyone is using OIDC? We aren't and are just using standard JDBC (for now).

Thanks again!

```
2022-09-18 15:04:51,460 WARN  [io.qua.oid.com.run.OidcCommonUtils] (vert.x-eventloop-thread-1) OIDC Server is not available:: io.quarkus.oidc.common.runtime.OidcEndpointAccessException
        at io.quarkus.oidc.common.runtime.OidcCommonUtils.lambda$discoverMetadata$2(OidcCommonUtils.java:406)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
        at io.smallrye.mutiny.vertx.DelegatingHandler.handle(DelegatingHandler.java:25)
        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:390)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:377)
```

**Comment by FroMage** [comment]
Hi, splitting out security into two modules in #57 solved this. I just tested it.
